#!/bin/sh

set -e

DBUSER="root"
DBPASS="431w"
DPHOST="localhost"
MYSQL=`which mysql`
MYSQLDUMP=`which mysqldump`

DBNAME=himalaya
BKDIR=/home/goodermuth/dev/websites/himalaya/dbdump
DUMPFILE=${BKDIR}/himalaya_`date +%Y-%m-%d`.sql.gz
TAG=dbbackup

# create the backup directory if it doesn't already exist
[ ! -d $BKDIR ] && mkdir -p $BKDIR || :

RECENT=`ls -rt $BACKDIR | tail -1`

$MYSQLDUMP -u $DBUSER -p${DBPASS} --opt $DBNAME | gzip > $DUMPFILE
logger -t $TAG created database dump \`${DUMPFILE}\'

if [ -z "`diff $DUMPFILE $RECENT`" ]
then
	# new backup is identical to the most recent before it
	logger -t $TAG database dump \`${DUMPFILE}\' is identical to previous dump, removing
	rm $DUMPFILE
	exit 0
fi

echo "${DUMPFILE}"

exit 0
