#!/bin/bash

set -e 

DBNAME="himalaya"
DBUSER="root"
DBPASS="431w"
AUCTIONS=/tmp/finished_acutions
SITEURL=himalaya.goodermuth.com

# terminate an auction by item_id
# usage: terminate item_id
function terminate()
{
	LOSERSFILE=/tmp/auction_${1}_losers
	WINFILE=/tmp/auction_${1}_winner
	SELLERFILE=/tmp/auction_${1}_seller
	ITEMFILE=/tmp/auction_${1}_item
	TOSELLER=/tmp/auction_${1}_seller_email.html
	TOWINNER=/tmp/auction_${1}_winner_email.html
	TOLOSER=/tmp/auction_${1}_loser_email.html
	CATXML=/home/goodermuth/dev/websites/himalaya/common/categories.xml

	rm -f $LOSERSFILE $WINFILE $SELLERFILE $ITEMFILE

	# get emails of all non-winning bidders
	mysql -u $DBUSER -p${DBPASS} -e \
		"SELECT E.email
	         FROM   Emails E, Has_Bid H, Auctions A
		 WHERE  H.item_id=$1 AND H.item_id=A.item_id AND 
		        E.username=H.bidder AND H.bidder <> A.recent_bidder
		 INTO   OUTFILE '$LOSERSFILE' 
		        LINES TERMINATED BY '\\n'" $DBNAME

	# get reserve price, last bid, winner's email, 
	#   first address, first credit card
	mysql -u $DBUSER -p${DBPASS} -e \
		"SELECT A.recent_bidder, A.recent_bid, A.reserve_price,
	                E.email, D.street, Z.city, Z.zstate, D.zip, 
			C.cnumber, C.ctype, C.cname
		 FROM   Auctions A, Emails E, Addresses D, 
		        Has_Card H, ZIP_Codes Z, Credit_Cards C
		 WHERE  A.item_id=$1 AND E.username=A.recent_bidder AND
		        A.recent_bidder=D.username AND Z.zip=D.zip AND
			A.recent_bidder=H.username AND H.cnumber=C.cnumber
		 LIMIT  1
		 INTO   OUTFILE '$WINFILE' FIELDS TERMINATED BY ';'
		        LINES TERMINATED BY '\\n'" $DBNAME

	# get email of seller
	mysql -u $DBUSER -p${DBPASS} -e \
		"SELECT S.username, E.email
		 FROM   Emails E, Sale_Items S
		 WHERE  S.item_id=$1 AND E.username=S.username
		 INTO   OUTFILE '$SELLERFILE' FIELDS TERMINATED BY ';'
		        LINES TERMINATED BY '\\n'" $DBNAME
	
	# get item information
	mysql -u $DBUSER -p${DBPASS} -e \
		"SELECT P.p_name, S.scondition, Z.city, Z.zstate, S.shipping_zip
	         FROM   Products P, Sale_Items S, ZIP_Codes Z
		 WHERE  item_id=$1 AND S.product_id=P.product_id AND 
		        S.shipping_zip=Z.zip
		 INTO   OUTFILE '$ITEMFILE' FIELDS TERMINATED BY ';'
		        LINES TERMINATED BY '\\n'" $DBNAME

	WINNER=`cat $WINFILE | cut -d';' -f1`
	LASTBID=`cat $WINFILE | cut -d';' -f2`
	RESERVE=`cat $WINFILE | cut -d';' -f3`
	WINEMAIL=`cat $WINFILE | cut -d';' -f4`
	TOSTREET=`cat $WINFILE | cut -d';' -f5`
	TOCITY=`cat $WINFILE | cut -d';' -f6`
	TOSTATE=`cat $WINFILE | cut -d';' -f7`
	TOZIP=`cat $WINFILE | cut -d';' -f8`
	CARDNUM=`cat $WINFILE | cut -d';' -f9`
	CARDTYPE=`cat $WINFILE | cut -d';' -f10`
	CARDNAME=`cat $WINFILE | cut -d';' -f11`
	SELLER=`cat $SELLERFILE | cut -d';' -f1`
	SELLEMAIL=`cat $SELLERFILE | cut -d';' -f2`
	PNAME=`cat $ITEMFILE | cut -d';' -f1`
	CONDITION=`cat $ITEMFILE | cut -d';' -f2`
	FROMCITY=`cat $ITEMFILE | cut -d';' -f3`
	FROMSTATE=`cat $ITEMFILE | cut -d';' -f4`
	FROMZIP=`cat $ITEMFILE | cut -d';' -f5`

	if [ -z $WINNER ]
	then
		# no bids were placed on the item, just email the seller
		echo "
<html>
	<head>
		<title>Himalaya.biz - auction over</title>
	</head>
	<body>
		<h2>Your auction has ended</h2>
		You are receiving this message because the item you had for
		auction on Himalaya.biz -- $PNAME -- was not sold, because no 
		one placed a bid on the item.<br><br>

		As a result, the item has been removed from our inventory, but 
		feel free to 
		<a href=\"$SITEURL/members/sellitem.php\">post it again</a> as 
		an auction or a sale.<br><br>
		
		Thanks for shopping with Himalaya.biz!<br><br>
	  
		-- The Himalaya Team<br>
	</body>
</html>" > $TOSELLER

		if [ -n $SELLEMAIL ]  # seller is a registered user
		then
			messagesend $SELLEMAIL $TOSELLER "end of auction"
		fi
	elif [ $RESERVE -gt $LASTBID ]
	then
		# if the reserve price was not met
		
		# get price as 2-digit dollar value
		echo reserve = $RESERVE
		RSCALED=`echo "scale=2; $RESERVE / 100" | bc`
		ADJPRICE=`printf "%.2f" $RSCALED`
		
		echo auction failed, item_id = $1
		echo reserve price $ADJPRICE is greater than last bid $LASTBID

		mysql -u $DBUSER -p${DBPASS} -e \
			"DELETE FROM Auctions WHERE item_id=$1; 
		         DELETE FROM Sale_Items WHERE item_id=$1" $DBNAME
	
		# rebuild the categories xml file
		/usr/local/bin/catxml.sh > $CATXML

		# notify seller and highest bidder
		echo "
<html>
	<head>
		<title>Himalaya.biz - auction over</title>
	</head>
	<body>
		<h2>Your auction has ended</h2>
		You are receiving this message because the item you had for
		auction on Himalaya.biz -- $PNAME -- was not sold, because  
		the winning bid did not meet or exceed your reserve price.
		<br><br>

		As a result, the item has been removed from our inventory, but 
		feel free to 
		<a href=\"$SITEURL/members/sellitem.php\">post it again</a> as 
		an auction or a sale.<br><br>
		
		Thanks for shopping with Himalaya.biz!<br><br>
	  
		-- The Himalaya Team<br>
	</body>
</html>" > $TOSELLER

		echo "
<html>
	<head>
		<title>Himalaya.biz - auction over</title>
	</head>
	<body>
		<h2>Your auction has ended</h2>
		You are receiving this message because the item you won an 
		auction for on Himalaya.biz -- $PNAME -- was not sold, 
		because your winning bid did not meet the seller's hidden 
		reserve price.<br><br

		Thanks for shopping with Himalaya.biz!<br><br>
	  
		-- The Himalaya Team<br>
	</body>
</html>" > $TOSELLER
		
		
	else
		echo reserve = $RESERVE
		RSCALED=`echo "scale=2; $RESERVE / 100" | bc`
		ADJPRICE=`printf "%.2f" $RSCALED`
		echo auction succeeded, item_id = $1
		echo reserve price $ADJPRICE is less than or equal to last bid $LASTBID
		
		# create an orders record
		mysql -u $DBUSER -p${DBPASS} -e \
			"INSERT INTO Orders 
		        VALUES ($1, '$WINNER', 0, '$TODAY', $LASTBID, 
			        '$TOSTREET', '$TOZIP', '$CARDNUM')" $DBNAME

		echo "
<html>
	<head>
		<title>Himalaya.biz - auction over</title>
	</head>
	<body>
		<h2>You won an auction!</h2>
		You are receiving this message because you won an item for 
		auction on Himalaya.biz! Upon ending the auction, we took your 
		default address and credit card information in order to 
		complete the transaction.<br><br>

		Here's the information for the item, as well as the billing 
		and shipping information:<br><br>

		<h3>Item Information</h3>
		<table>
			<tr>
				<td>Item Name:</td>
				<td>$PNAME</td>
			</tr>
			<tr>
				<td>Seller:</td>
				<td>$SELLER</td>
			</tr>
			<tr>
				<td>Item Price:</td>
				<td>\$$ADJPRICE</td>
			</tr>
	    <tr>
	      <td>Shipping from:</td>
	      <td>$FROMCITY, $FROMSTATE $FROMZIP</td>
	    </tr>
	  </table>
	
	  <h3>Billing Information</h3>
	  <table>
	    <tr> 
	      <td>Name on Card:</td>
	      <td>$CARDNAME</td>
	    </tr>
	    <tr>
	      <td>Card Type:</td>
	      <td>$CARDTYPE</td>
	    </tr>
	    <tr>
	      <td>Card Number:</td>
	      <td>$CARDNUM</td>
	    </tr>
	  </table>
	
	  <h3>Shipping Information</h3>
	  <table>
	    <tr>
	      <td>Full Name:</td>
	      <td>$TONAME</td>
	    </tr>
	    <tr>
	      <td>Street Address:</td>
	      <td>$TOSTREET</td>
	    </tr>
	    <tr>
	      <td>City, State:</td>
	      <td>$TOCITY, $TOSTATE</td>
	    </tr> 
	    <tr>
	      <td>ZIP code:</td>
	      <td>$TOZIP</td>
	    </tr>
	  </table>
	  <br><br>
	  
	  Be on the lookout for more emails as your order progresses. 
	  Thanks for shopping with Himalaya.biz!<br><br>
	  
	  -- The Himalaya Team<br>
	</body>
</html>" > $TOWINNER
		
		echo "
<html>
	<head>
		<title>Himalaya.biz - auction over</title>
	</head>
	<body>
		<h2>Your auction has ended</h2>
		You are receiving this message because the item you had for
		auction on Himalaya.biz -- $PNAME -- has been sold!<br><br>

		Please send your item to the Himalaya.biz shipping facility 
		within two weeks, or the order will be voided. The address to 
		send your item to is:<br><br>
		
		Himalaya.biz Shipping<br>
		13 Main St<br>
		State College, PA 16801<br><br>
		
		Thanks for shopping with Himalaya.biz!<br><br>
	  
		-- The Himalaya Team<br>
	</body>
</html>" > $TOSELLER

		echo "
<html>
	<head>
		<title>Himalaya.biz - auction over</title>
	</head>
	<body>
		<h2>Your auction has ended</h2>
		You are receiving this message because the item you had bid
		on at Himalaya.biz -- $PNAME -- has been sold, but you did not 
		place the winning bid.<br><br>
		
		Feel free to try to win some other 
		<a href=\"$SITEURL/items/browse.php\">auctions</a>!<br><br>
		
		Thanks for shopping with Himalaya.biz!<br><br>

		-- The Himalaya Team<br>
	</body>
</html>" > $TOLOSER

		if [ -n $SELLEMAIL ]  # seller is a registered user
		then
			messagesend $SELLEMAIL $ENDFILE \
			            "your auction item has sold!"
		fi
		messagesend $WINEMAIL $TOWINNER "you won an auction!"
	fi

	cat $LOSERSFILE | while read EMAIL
	do
		messagesend $EMAIL $TOLOSER "you did not win an auction"
	done

	echo
}

#####################

rm -f $AUCTIONS

TIME=`date --date "2 weeks ago" +"%F %T"`
TODAY=`date +%F`

mysql -u $DBUSER -p${DBPASS} -e \
	"SELECT A.item_id 
	 FROM   Auctions A 
	 WHERE  A.end_date < \"$TIME\" 
	 INTO   OUTFILE '$AUCTIONS' LINES TERMINATED BY '\\n'" $DBNAME

cat $AUCTIONS | while read LINE
do
	terminate $LINE
done

exit 0
