#!/bin/sh
# build the database creation file

set -e

DBUSER=root
DBNAME=himalaya
DBPASS=431w
DROPBOX=/home/goodermuth/Dropbox/cmpsc431_project
DUMPFILE=/home/goodermuth/dev/websites/himalaya/dbdump/init_backup_`date +%s`.sql.gz
DROPFILE=/home/goodermuth/dev/websites/himalaya/common/forms/categories.html
SELLFORM=/home/goodermuth/dev/websites/himalaya/common/forms/sellitem
INIT=db_init.sql

# dump db in case changes were unintentionally erased
mysqldump -u $DBUSER -p${DBPASS} --opt $DBNAME | gzip > $DUMPFILE

printf "DROP DATABASE $DBNAME;\nCREATE DATABASE $DBNAME;\n\nUSE $DBNAME;" > $INIT
cat $DROPBOX/phase3/relations.sql $DROPBOX/phase3/inserts.sql >> $INIT

# remove Windows line endings
sed -e 's///g' $INIT > temp; mv temp $INIT

# relink INIT in Dropbox
rm -f $DROPBOX/$INIT
link $INIT $DROPBOX/$INIT

mysql -u $DBUSER -p${DBPASS} $DBNAME < $INIT
echo created relations in $DBNAME db
echo creating category dropdown menu...
./catlist.sh > $DROPFILE
cat ${SELLFORM}1.form $DROPFILE ${SELLFORM}2.form > $SELLFORM.form
echo remaking zip code parser...
cd ..
make > /dev/null
mv zipparse scripts
cd - > /dev/null
echo adding ZIP code records...
./zipparse root ../zip.txt

echo "IMPORTANT: in case any changes were unintentionally overwritten by this \
reinitialization, a dump of the $DBNAME database was created as $DUMPFILE
if you do not need that dump, please remove it"
